---
- hosts: inetRouter
  become: true
  tasks:
  - name: Config inetRouter Bond
    shell: |
      nmcli con add type bond con-name bond0 ifname bond0 bond.options "mode=1,miimon=100,fail_over_mac=1" ip4 192.168.50.11/24
      nmcli con add type bond-slave ifname eth1 master bond0
      nmcli con add type bond-slave ifname eth2 master bond0
      nmcli connection up bond-slave-eth1
      nmcli connection up bond-slave-eth2
      nmcli con up bond0

- hosts: centralRouter
  become: true
  tasks:
  - name: Config centralRouter Bond and VLAN 
    shell: |
      nmcli con add type bond con-name bond0 ifname bond0 bond.options "mode=1,miimon=100,fail_over_mac=1" ip4 192.168.50.10/24
      nmcli con add type bond-slave ifname eth1 master bond0
      nmcli con add type bond-slave ifname eth2 master bond0
      nmcli connection up bond-slave-eth1
      nmcli connection up bond-slave-eth2
      nmcli con up bond0
      nmcli con add type vlan ifname VLAN10 dev eth3 id 10 ip4 10.10.10.10/24
      nmcli con add type vlan ifname VLAN20 dev eth3 id 20 ip4 10.10.10.20/24

- hosts: testServer1
  become: true
  tasks:
  - name: Config VLAN 10
    shell: |
      nmcli con add type vlan ifname VLAN10 dev eth1 id 10 ip4 10.10.10.1/24

- hosts: testClient1
  become: true
  tasks:
  - name: Config VLAN 10
    shell: |
      nmcli con add type vlan ifname VLAN10 dev eth1 id 10 ip4 10.10.10.254/24

- hosts: testServer2
  become: true
  tasks:
  - name: Config VLAN 20
    shell: |
      nmcli con add type vlan ifname VLAN20 dev eth1 id 20 ip4 10.10.10.1/24

- hosts: testClient2
  become: true
  tasks:
  - name: Config VLAN 20
    shell: |
      nmcli con add type vlan ifname VLAN20 dev eth1 id 20 ip4 10.10.10.254/24
