# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos8"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "systemd" do |nfss|
    nfss.vm.network "private_network", ip: "192.168.56.10", virtualbox__intnet: "net1"
    nfss.vm.hostname = "systemd"
    nfss.vm.provision "shell", path: "systemd.sh"
  end
end

