---
- hosts: all
  become: true
  tasks:
  - name: install traceroute
    apt:
      name: traceroute
      state: present
      update_cache: true
      
  - name: disable UFW
    systemd:
      name: ufw
      state: stopped
      enabled: no
    when: (ansible_hostname == "inetRouter") 

  - name: Set up NAT on inetRouter
    template: 
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
    with_items:
      - { src: "files/iptables_rules.ipv4", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
      - { src: "files/iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
    when: (ansible_hostname == "inetRouter")

  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present
    when: "'routers' in group_names"

  - name: disable default route
    template: 
      src: "files/00-installer-config.yaml"
      dest: "/etc/netplan/00-installer-config.yaml"
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname != "inetRouter") 

  - name: add default gateway for centralRouter
    template: 
      src: "files/50-vagrant_{{ansible_hostname}}.yaml"
      dest: "/etc/netplan/50-vagrant.yaml"
      owner: root
      group: root
      mode: 0644

  - name: restart all hosts
    reboot:
      reboot_timeout: 600
