ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/22.04"
   # config.vm.box_version = "22.04"

    config.vm.provider :virtualbox do |v|
        v.memory = 512
        v.cpus = 1
    end

    boxes = [
        { :name => "web",
          :ip => "192.168.56.10",
        },
        { :name => "log",
          :ip => "192.168.56.15",
        }
    ]

    boxes.each do |opts|
        config.vm.define opts[:name] do |config|
            config.vm.hostname = opts[:name]
            config.vm.network "private_network", ip: opts[:ip]

            if opts[:name] == boxes.last[:name]
                config.vm.provision "ansible" do |ansible|
                    ansible.playbook = "ansible/playbook.yml"
                    ansible.inventory_path = "ansible/inventory"
                    ansible.host_key_checking = "false"
                    ansible.limit = "all"
                end
            end
        end
    end
end
