MACHINES = {
  :"ubuntu" => {
              :box_name=>'ubuntu',
	      :cpus => 2,
              :memory => 1024,
              :ip => "192.168.57.10",
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.network "private_network", ip: boxconfig[:ip]
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
      box.vm.provision "file", source: "./login.sh", destination: "/tmp/login.sh"
      box.vm.provision "shell", inline: <<-SHELL
          sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config
          systemctl restart sshd.service
	  useradd otusadm && useradd otus
	  echo "otusadm:Qwerty123" | chpasswd  && echo "otus:Qwerty123" | chpasswd
	  groupadd -f admin
	  usermod otusadm -a -G admin && usermod root -a -G admin && usermod vagrant -a -G admin
	  mv /tmp/login.sh /usr/local/bin/login.sh
	  chmod +x /usr/local/bin/login.sh	  
	  SHELL
    end
  end
end
